config/routes.rb
LdapRegister::Application.routes.draw do

  resource :directories
  get '/directories/index', to: 'directories#index', as:'directories_index' 
  post '/directories/search_user', to: 'directories#search_user', as:'search_user' 

  root :to => "application#index"

end

app/models/directory.rb
class Directory < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :nome
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


 


end

app/controllers/directories_controller.rb
require 'rubygems'
require 'net/ldap'
require 'net/smtp'

class DirectoriesController < ApplicationController

  $host=
    $port=
    $userName=
    $password=
    $dc=

  def read_file
    arquivo = File.open "config/ldap.yml", "r"

    while  !arquivo.eof?

      word = arquivo.readline.strip
      word=word.split /:/ , 2

      if word[0] == "host"
        $host= word[1].strip
      end

      if word[0] =="port"
        $port= word[1].strip
      end

      if word[0] =="userName"
        $userName= word[1].strip
      end

      if word[0] =="password"
        $password= word[1].strip
      end

      if word[0] =="dc"
        $dc = word[1].strip
      end

    end

  end


  def init_ldap
    read_file
    ldap = Net::LDAP.new :host => $host,
      :port => $port,
    :auth => {
      :method => :simple,
      :username => $userName,
      :password => $password
    }
  end

  def cadastrar_usuario ldap, dn, attributes
    ldap.open do | ldap |
      ldap.add(:dn => dn , :attributes => attributes)
    end
  end


  def update
    ldap = init_ldap

    password = params[:password]
    password_confirmation = params[:password_confirmation]

    ops = [[:replace, :userPassword , password ]]

    if password != password_confirmation
      flash[:error] = 'Nova senha e Confirmar nova senha devem ser idênticos'
      redirect_to(edit_directories_path)
    elsif ldap.bind  
      ldap.modify  :dn => $dn , :operations => ops
      redirect_to(root_path, notice: 'Usuario atualizado com sucesso' )
    else
      flash[:error] = 'Não foi possível atualizar a senha'
      redirect_to(edit_directories_path)
    end

  end


  def search_user
    user_email = params[:email]

    filter = Net::LDAP::Filter.eq("mail",user_email)
    attrs=["mail","cn","sn","dn","uid","givenName","objectclass"]

    ldap = init_ldap
    if ldap.bind
      ldap.search(:base => $dc, :filter => filter,:attributes => attrs , :return_result => true) do |user|
        $dn= "#{user.dn}"
        $uid = "#{user.uid[0]}"
        $givenName = "#{user.givenName[0]}"
        $sn = "#{user.sn[0]}"
        $cn = "#{user.cn[0]}"
        $mail="#{user.mail[0]}"
      end
    end

    if  $dn
      redirect_to(edit_directories_path, notice: 'Usuario encontrado com sucesso' )
    else
      flash[:error] = 'Usuário não encontrado'
      redirect_to(root_path)
    end

  end

  def is_registered ldap, login, password
    @result = ldap.bind_as(
      :base => $dc,
      :filter => "(uid=#{login})",
      :password => password
    )
  end

  def set_attributes login, nome, sobreNome, email, password

    attributes = {
      :uid => login,
      :objectClass => [ "organizationalPerson",
                        "person",
                        "top",
                        "inetOrgPerson",
                        "shadowAccount"],
      :sn => sobreNome,
      :givenName => nome,
      :mail => email ,
      :cn => "#{nome} #{sobreNome}" ,
      :userPassword => "#{password}"
    }

  end


  def create

    login = params[:login]
    nome = params[:nome]
    sobreNome = params[:sobreNome]
    email = params[:email]
    password = params[:password]
    password_confirmation = params[:password_confirmation]

    if password_confirmation == password
      dn = "uid=#{login},ou=users,#{$dc}"
      ldap = init_ldap
      attributes = set_attributes login,nome,sobreNome,email,password
      cadastrar_usuario ldap, dn, attributes
      is_registered ldap, login, password
    else
      flash[:error] = 'Campo senha deve ser idêntico ao confirmar senha'
    end

  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  $redmine_path="#"
  $gitlab_path="#"

  def gitlab_link
	reference_link 
	return $gitlab_path	
  end

  def redmine_link
	reference_link
	return $redmine_path
  end
	
  def  reference_link
	if $redmine_path == "#" || $gitlab_path == "#"

	  arquivo = File.open "config/references.yml" , "r"

	  while  !arquivo.eof?
        	word = arquivo.readline.strip
        	word=word.split /:/,2

        	if word[0] == "redmine"
                  $redmine_path= "http://#{word[1].strip}"
        	end
        	if word[0] =="gitlab"
        	  $gitlab_path = "http://#{word[1].strip}"
       		end
           end
        end
  end
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/views/application/index.html.erb
<div class="hero-unit" align="center">
  <h1>Lab-Sei</h1>
    <p>Cadastro de usuários para utilização das ferramentas Redmine e Gitlab</p>
    <p>

      <%= link_to image_tag("Redmine_logo_0.png", :alt => "rss feed") , redmine_link , :target => "_blank"%>
      
      <%= link_to image_tag("gitlab_0.png", :alt => "rss feed") , gitlab_link , :target => "_blank" %>

    </p>
</div>

app/views/directories/_form.html.erb
<script type="text/javascript">
	
	document.addEventListener("DOMContentLoaded", function() {
	    var elements = document.getElementsByTagName("INPUT");
	    for (var i = 0; i < elements.length; i++) {
	        elements[i].oninvalid = function(e) {
	            e.target.setCustomValidity("");
	            if (!e.target.validity.valid ) {
	                e.target.setCustomValidity("Este campo não pode ficar em branco");
	            }
	        };
	        elements[i].oninput = function(e) {
	            e.target.setCustomValidity("");
	        };
	    }
	})

</script>

<%= form_tag  directories_path, method: :post do  %>
		
		<div class="field">
			<%= label_tag "Login"%>
   			<%= text_field_tag 'login', nil,:required => true , :placeholder => "Login"%>
   		</div>
	
		<div class="field">
			<%= label_tag "Nome"%> 
			<%= text_field_tag 'nome' , nil ,:required => true,:placeholder => "Nome" %>
   		</div>
		
		<div class="field">
			
			<%= label_tag "SobreNome"%>
			<%= text_field_tag 'sobreNome' ,nil , :required => true,:placeholder => "SobreNome" %>
		</div>
		
		<div class="field">
			<%= label_tag "Email"%>
   			<%= email_field_tag 'email' , nil, :required => true, :placeholder => "seuemail@.com" %>
   		</div>

		<div class="field">
			<%= label_tag "Senha"%>
   			<%= password_field_tag "password", nil ,:required => true %>
   		</div>		

   		<div class="field">
			<%= label_tag "Confrimar senha"%>
   			<%= password_field_tag "password_confirmation", nil ,:required => true %>
   		</div>		


		  <%= button_tag :class => 'btn-success btn', :id => 'cadastrar' do %>
            <i class=' icon-white icon-user'></i> Cadastrar
        <% end %>

	
<% end  %>

app/views/directories/_form_edit.html.erb
<script type="text/javascript">
	
	document.addEventListener("DOMContentLoaded", function() {
	    var elements = document.getElementsByTagName("INPUT");
	    for (var i = 0; i < elements.length; i++) {
	        elements[i].oninvalid = function(e) {
	            e.target.setCustomValidity("");
	            if (!e.target.validity.valid ) {
	                e.target.setCustomValidity("Este campo não pode ficar em branco");
	            }
	        };
	        elements[i].oninput = function(e) {
	            e.target.setCustomValidity("");
	        };
	    }
	})

</script>

<%= form_tag  directories_path, method: :put do  %>
		<h2>Editar Cadastro</h2>
		<div class="field">

			<%= label_tag "Login"%>
   			<%= text_field_tag 'login', $uid ,:required => true , :placeholder => "Login" , :disable => true%>
   		</div>
	
		<div class="field">
			<%= label_tag "Nome"%> 
			<%= text_field_tag 'nome' , $givenName ,:required => true,:placeholder => "Nome" , :disable => true  %>
   		</div>
		
		<div class="field">
			<%= label_tag "SobreNome"%>
			<%= text_field_tag 'sobreNome' , $sn , :required => true,:placeholder => "SobreNome", :disable=> true %>
		</div>
		
		<div class="field">
			<%= label_tag "Email"%>
   			<%= email_field_tag 'email' ,  $mail , :required => true, :placeholder => "seuemail@.com", :disable => true %>
   		</div>
		
		<div class="field">
			<%= label_tag "Nova Senha"%>
   			<%= password_field_tag "password", nil ,:required => true %>
   		</div>		

		<div class="field">
			<%= label_tag "Confirmar Nova Senha"%>
   			<%= password_field_tag "password_confirmation", nil ,:required => true %>
   		</div>		

		  <%= button_tag :class => 'btn-success btn', :id => 'cadastrar' do %>
            <i class=' icon-white icon-edit'></i> Editar
        <% end %>

	
<% end  %>

app/views/directories/_form_recover.html.erb
<%=  form_tag url_for(:controller => 'directories', :action => 'search_user')  do  %>
		
		<div class="field">
			<h2> Digite seu email</h2>
			<%= label_tag "email"%>
   			<%= email_field_tag 'email', nil,:required => true , :placeholder => "Buscar por email"%>
   		</div>

		  <%= button_tag :class => 'btn-info btn', :id => 'cadastrar' do %>
            <i class=' icon-white icon-search'></i> Buscar
        <% end %>
	
<% end  %>

app/views/directories/create.html.erb
<html>

	<% if @result %> 
		<div class="alert alert-success"> Usuário Cadastrado com sucesso. Agora você já pode logar no REDMINE/GITLAB</div>	
	<% else %>
		<div class="alert alert-error"> Erro ao tentar cadastrar usuário.</div>
		<%= render 'form' %>
	
	<% end %>

</html>

app/views/directories/edit.html.erb
<%= render 'form_edit' %>

app/views/directories/index.html.erb
<%= render 'form_recover' %>

app/views/directories/new.html.erb
<div class="conteiner-fluid">
<div class="form-divs">
<div class="border-form-div">

	<%= render 'form'%>

</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Registro-LDAP" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->


    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path%>">Registro de Usuários</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">

              <li>
                <%= link_to redmine_link do %>
                  <i class="fa fa-comment"></i> REDMINE  
                <% end %>
              </li>
              
              <li>
                <%= link_to gitlab_link do %>
                  <i class="fa fa-github"></i> GITLAB  
                <% end %>
              </li>
              

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              
                <%= link_to new_directories_path do %>
                  <i class="fa fa-user"></i> Cadastrar Usuário
                <% end %><br> 
 
                
                 <%= link_to directories_index_path do %>
                  <i class="fa fa-edit"></i> Editar  Usuário
                <% end %>

                <!--
                <%= link_to "#" do %><br>
                  <i class="fa fa-search"></i> Pesquisar  Usuário
                <% end %> -->

            </ul>
          </div><!--/.well -->
        </div><!--/span-->

        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->


      <footer class="span9">
              <p>&copy; LAB SEI</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>